---
- name: Install firewalld packages
  become: true
  yum:
    name: "{{ firewall_app_name }}"
    state: present
- name: Open port 80 for http access
  become: true
  firewalld:
    service: "{{ http_port }}"
    permanent: yes
    state: enabled
  notify: Restart firewalld
