version: "3.9"
   
services:
  database:
    build: ./database
    networks:
      back:
        ipv4_address: 172.16.238.4
    volumes:
      - /var/db/postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./lib_catalog
    depends_on:
      - database
    networks:
      back:
        ipv4_address: 172.16.238.3


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - database
    networks:
      back:
        ipv4_address: 172.16.238.2
      default:

networks:
#Internal-only network for access to backend and database
  back:
    driver: bridge
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
#External network for frontend
  default:
    driver: bridge
