---
controls:
  hosts:
    control.example.com:
      ansible_host: 10.129.0.4
nodes:
  hosts:
    node1.example.com:
      ansible_host: 10.129.0.34
    node2.example.com:
      ansible_host: 10.129.0.26
grub:
  hosts:
    node1.example.com:
